spring:
  application:
    name: multi-tenant
  datasource:
    tenant1:
#      url: jdbc:h2:mem:tenant1_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      url: jdbc:h2:mem:tenant1_db;INIT=RUNSCRIPT FROM 'classpath:h2init/schema.sql'\;RUNSCRIPT FROM 'classpath:h2init/data.sql'
      username: sa
      password:
      driver-class-name: org.h2.Driver
    tenant2:
#      url: jdbc:h2:mem:tenant2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      url: jdbc:h2:mem:tenant2_db;INIT=RUNSCRIPT FROM 'classpath:h2init/schema.sql'\;RUNSCRIPT FROM 'classpath:h2init/data2.sql'
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml